export interface FieldMapping {
  field: string
  column: string
}

export const MONITORING_MAPPING: FieldMapping[] = [
  { field: "tglPermintaan", column: "Tgl Permintaan" },
  { field: "kodeLotLelang", column: "Kode Lot Lelang" },
  { field: "idPengajuan", column: "ID Pengajuan" },
  { field: "tanggalPengambilan", column: "Tanggal Pengambilan" },
  { field: "jenisLayanan", column: "Jenis Layanan" },
  { field: "nomorDokumen", column: "Nomor Dokumen" },
  { field: "tanggalDokumen", column: "Tanggal Dokumen" },
  { field: "statusProses", column: "Status Proses" },
  { field: "deletedAt", column: "Tgl Dihapus" },
  { field: "deletedBy", column: "Dihapus Oleh" },
]

export const KUITANSI_MAPPING: FieldMapping[] = [
  { field: "tiketKPHL", column: "Tiket KPHL" },
  { field: "kodeTiketKPHL", column: "Kode Tiket KPHL" },
  { field: "idKPHL", column: "ID KPHL" },
  { field: "noPengajuan", column: "No Pengajuan" },
  { field: "tglPermintaan", column: "Tgl Permintaan" },
  { field: "emailAddress", column: "Email Address" },
  { field: "namaPemohon", column: "Nama Pemohon" },
  { field: "nomorIdentitasPemohon", column: "Nomor Identitas Pemohon" },
  { field: "alamatPemohon", column: "Alamat Pemohon" },
  { field: "nomorWhatsappPemohon", column: "Nomor Whatsapp Pemohon" },
  { field: "jenisPemohon", column: "Jenis Pemohon" },
  { field: "namaPemberiKuasa", column: "Nama Pemberi Kuasa" },
  { field: "nomorIdentitasPemberiKuasa", column: "Nomor Identitas Pemberi Kuasa" },
  { field: "alamatPemberiKuasa", column: "Alamat Pemberi Kuasa" },
  { field: "nomorWhatsappPemberiKuasa", column: "Nomor Whatsapp Pemberi Kuasa" },
  { field: "jenisIdentitasPemberiKuasa", column: "Jenis Identitas Pemberi Kuasa" },
  { field: "dokumenIdentitasPemberiKuasa", column: "Dokumen Identitas Pemberi Kuasa" },
  { field: "verifDokIDPemberiKuasa", column: "Verif Dok. ID Pemberi Kuasa" },
  { field: "suratKuasa", column: "Surat Kuasa" },
  { field: "verifSuratKuasa", column: "Verif Surat Kuasa" },
  { field: "jenisIdentitasPemohon", column: "Jenis Identitas Pemohon" },
  { field: "dokumenIDPemohon", column: "Dokumen ID Pemohon" },
  { field: "verifDokumenID", column: "Verif Dokumen ID" },
  { field: "tanggalPelunasanPembayaran", column: "Tanggal Pelunasan Pembayaran" },
  { field: "buktiPelunasan", column: "Bukti Pelunasan" },
  { field: "verifBuktiPelunasan", column: "Verif Bukti Pelunasan" },
  { field: "tanggalPengambilan", column: "Tanggal Pengambilan" },
  { field: "waktuPengambilan", column: "Waktu Pengambilan" },
  { field: "statusPermohonan", column: "Status Permohonan" },
  { field: "keteranganDitolak", column: "Keterangan Ditolak" },
  { field: "statusProses", column: "Status Proses" },
  { field: "tiket", column: "Tiket" },
  { field: "kodeLotLelang", column: "Kode Lot Lelang" },
  { field: "nomorKuitansi", column: "Nomor Kuitansi" },
  { field: "tanggalKuitansi", column: "Tanggal Kuitansi" },
  { field: "jarak", column: "jarak" },
  { field: "mergedDocIDKuitansiPembayaranHargaLelang", column: "Merged Doc ID - Kuitansi Pembayaran Harga Lelang" },
  { field: "mergedDocURLKuitansiPembayaranHargaLelang", column: "Merged Doc URL - Kuitansi Pembayaran Harga Lelang" },
  { field: "linkToMergedDocKuitansiPembayaranHargaLelang", column: "Link to merged Doc - Kuitansi Pembayaran Harga Lelang" },
  { field: "documentMergeStatusKuitansiPembayaranHargaLelang", column: "Document Merge Status - Kuitansi Pembayaran Harga Lelang" },
  { field: "mergedDocIDAutoKuitansi", column: "Merged Doc ID - auto Kuitansi" },
  { field: "bantuAutoKuitansi", column: "bantu_auto_kuitansi" },
  { field: "mergedDocURLAutoKuitansi", column: "Merged Doc URL - auto Kuitansi" },
  { field: "linkToMergedDocAutoKuitansi", column: "Link to merged Doc - auto Kuitansi" },
  { field: "documentMergeStatusAutoKuitansi", column: "Document Merge Status - auto Kuitansi" },
  { field: "mergedDocIDAutoNotifKuitansi", column: "Merged Doc ID - auto notif kuitansi" },
  { field: "mergedDocURLAutoNotifKuitansi", column: "Merged Doc URL - auto notif kuitansi" },
  { field: "linkToMergedDocAutoNotifKuitansi", column: "Link to merged Doc - auto notif kuitansi" },
  { field: "documentMergeStatusAutoNotifKuitansi", column: "Document Merge Status - auto notif kuitansi" },
  { field: "mergedDocIDPenolakanKuitansi", column: "Merged Doc ID - penolakan kuitansi" },
  { field: "mergedDocURLPenolakanKuitansi", column: "Merged Doc URL - penolakan kuitansi" },
  { field: "linkToMergedDocPenolakanKuitansi", column: "Link to merged Doc - penolakan kuitansi" },
  { field: "documentMergeStatusPenolakanKuitansi", column: "Document Merge Status - penolakan kuitansi" },
  { field: "deletedAt", column: "Tgl Dihapus" },
  { field: "deletedBy", column: "Dihapus Oleh" },
]

export const KUTIPAN_RL_MAPPING: FieldMapping[] = [
  { field: "tiketKRL", column: "Tiket K-RL" },
  { field: "kodeTiketKRL", column: "Kode Tiket K-RL" },
  { field: "idKRL", column: "ID K-RL" },
  { field: "noPengajuan", column: "No Pengajuan" },
  { field: "tglPermintaan", column: "Tgl Permintaan" },
  { field: "namaPemohon", column: "Nama Pemohon" },
  { field: "emailAddress", column: "Email Address" },
  { field: "nomorIdentitasPemohon", column: "Nomor Identitas Pemohon" },
  { field: "alamatPemohon", column: "Alamat Pemohon" },
  { field: "nomorWhatsappPemohon", column: "Nomor Whatsapp Pemohon" },
  { field: "jenisPemohon", column: "Jenis Pemohon" },
  { field: "namaPemberiKuasa", column: "Nama Pemberi Kuasa" },
  { field: "nomorIdentitasPemberiKuasa", column: "Nomor Identitas Pemberi Kuasa" },
  { field: "alamatPemberiKuasa", column: "Alamat Pemberi Kuasa" },
  { field: "nomorWhatsappPemberiKuasa", column: "Nomor Whatsapp Pemberi Kuasa" },
  { field: "jenisIdentitasPemberiKuasa", column: "Jenis Identitas Pemberi Kuasa" },
  { field: "dokumenIdentitasPemberiKuasa", column: "Dokumen Identitas Pemberi Kuasa" },
  { field: "verifDokIDPemberiKuasa", column: "Verif Dok. ID Pemberi Kuasa" },
  { field: "suratKuasa", column: "Surat Kuasa" },
  { field: "verifSuratKuasa", column: "Verif Surat Kuasa" },
  { field: "jenisDokumenIDPemohon", column: "Jenis Dokumen ID Pemohon" },
  { field: "dokumenIDPemohon", column: "Dokumen ID Pemohon" },
  { field: "verifDokumenID", column: "Verif Dokumen ID" },
  { field: "rincianUangHasilLelang", column: "Rincian Uang Hasil Lelang" },
  { field: "verifRincianUangHasilLelang", column: "Verif Rincian Uang Hasil Lelang" },
  { field: "buktiSetorPelunasan", column: "Bukti (setor) pelunasan" },
  { field: "verifBuktiSetorPelunasan", column: "Verif Bukti (setor) pelunasan" },
  { field: "kuitansiPembayaranHargaLelang", column: "Kuitansi Pembayaran Harga Lelang" },
  { field: "verifKuitansi", column: "Verif Kuitansi" },
  { field: "buktiSetorUangJaminanTandaTerimaUangJaminan", column: "Bukti setor uang jaminan/tanda terima uang jaminan" },
  { field: "verifBuktiSetorUangJaminanTandaTerimaUangJaminan", column: "Verif bukti setor uang jaminan/tanda terima uang jaminan" },
  { field: "objekLelang", column: "Objek Lelang" },
  { field: "sspdBPHTB", column: "SPPD BPHTB" },
  { field: "verifSSPDBPHTB", column: "Verif SPPD BPHTB" },
  { field: "tanggalPengambilan", column: "Tanggal Pengambilan" },
  { field: "waktuPengambilan", column: "Waktu Pengambilan" },
  { field: "statusPermohonan", column: "Status Permohonan" },
  { field: "keteranganDitolak", column: "Keterangan Ditolak" },
  { field: "statusProses", column: "Status Proses" },
  { field: "tiket", column: "Tiket" },
  { field: "kodeLotLelang", column: "Kode Lot Lelang" },
  { field: "nomorKutipan", column: "Nomor Kutipan" },
  { field: "tanggalKutipan", column: "Tanggal Kutipan" },
  { field: "jarak", column: "jarak" },
  { field: "mergedDocIDKutipanRisalahLelang", column: "Merged Doc ID - Kutipan Risalah Lelang" },
  { field: "mergedDocURLKutipanRisalahLelang", column: "Merged Doc URL - Kutipan Risalah Lelang" },
  { field: "linkToMergedDocKutipanRisalahLelang", column: "Link to merged Doc - Kutipan Risalah Lelang" },
  { field: "documentMergeStatusKutipanRisalahLelang", column: "Document Merge Status - Kutipan Risalah Lelang" },
  { field: "mergedDocIDAutoKutipanRL", column: "Merged Doc ID - auto Kutipan RL" },
  { field: "bantuAutoKutipan", column: "bantu_auto_kutipan" },
  { field: "linkToMergedDocAutoKutipanRL", column: "Link to merged Doc - auto Kutipan RL" },
  { field: "documentMergeStatusAutoKutipanRL", column: "Document Merge Status - auto Kutipan RL" },
  { field: "mergedDocIDAutoNotifKutipan", column: "Merged Doc ID - auto notif kutipan" },
  { field: "mergedDocURLAutoNotifKutipan", column: "Merged Doc URL - auto notif kutipan" },
  { field: "linkToMergedDocAutoNotifKutipan", column: "Link to merged Doc - auto notif kutipan" },
  { field: "documentMergeStatusAutoNotifKutipan", column: "Document Merge Status - auto notif kutipan" },
  { field: "mergedDocURLAutoKutipanRL", column: "Merged Doc URL - auto Kutipan RL" },
  { field: "deletedAt", column: "Tgl Dihapus" },
  { field: "deletedBy", column: "Dihapus Oleh" },
]

export const VALIDASI_PPH_MAPPING: FieldMapping[] = [
  { field: "tiketVPPh", column: "Tiket VPPh" },
  { field: "kodeTiketVPPh", column: "Kode Tiket VPPh" },
  { field: "idVPPh", column: "ID VPPh" },
  { field: "noPengajuan", column: "No Pengajuan" },
  { field: "tglPermintaan", column: "Tgl Permintaan" },
  { field: "emailAddress", column: "Email Address" },
  { field: "namaPemohon", column: "Nama Pemohon" },
  { field: "nomorIdentitasPemohon", column: "Nomor Identitas Pemohon" },
  { field: "alamatPemohon", column: "Alamat Pemohon" },
  { field: "nomorWhatsappPemohon", column: "Nomor Whatsapp Pemohon" },
  { field: "jenisPemohon", column: "Jenis Pemohon" },
  { field: "namaPemberiKuasa", column: "Nama Pemberi Kuasa" },
  { field: "nomorIdentitasPemberiKuasa", column: "Nomor Identitas Pemberi Kuasa" },
  { field: "alamatPemberiKuasa", column: "Alamat Pemberi Kuasa" },
  { field: "nomorWhatsappPemberiKuasa", column: "Nomor Whatsapp Pemberi Kuasa" },
  { field: "jenisIdentitasPemberiKuasa", column: "Jenis Identitas Pemberi Kuasa" },
  { field: "dokumenIdentitasPemberiKuasa", column: "Dokumen Identitas Pemberi Kuasa" },
  { field: "verifDokIDPemberiKuasa", column: "Verif Dok. ID Pemberi Kuasa" },
  { field: "suratKuasa", column: "Surat Kuasa" },
  { field: "verifSuratKuasa", column: "Verif Surat Kuasa" },
  { field: "jenisIdentitasPemohon", column: "Jenis Identitas Pemohon" },
  { field: "dokumenIDPemohon", column: "Dokumen ID Pemohon" },
  { field: "verifDokumenID", column: "Verif Dokumen ID" },
  { field: "nomorKuitansiPembayaranHargaLelang", column: "Nomor Kuitansi Pembayaran Harga Lelang" },
  { field: "kuitansiPembayaranHargaLelang", column: "Kuitansi Pembayaran Harga Lelang" },
  { field: "verifKuitansi", column: "Verif Kuitansi" },
  { field: "npwpPemenangLelang", column: "NPWP Pemenang Lelang" },
  { field: "uploadNPWPPemenangLelang", column: "Upload NPWP Pemenang Lelang" },
  { field: "ntpn", column: "NTPN" },
  { field: "slipSetorPPh", column: "Slip setor PPh" },
  { field: "verifSlipSetorPPh", column: "Verif Slip setor PPh" },
  { field: "nop", column: "NOP" },
  { field: "dokPBBBPHTB", column: "Dok. PBB / BPHTB" },
  { field: "alamatObjekLelang", column: "Alamat Objek Lelang" },
  { field: "verifDokPBBBPHTB", column: "Verif Dok. PBB / BPHTB" },
  { field: "tanggalPengambilan", column: "Tanggal Pengambilan" },
  { field: "waktuPengambilan", column: "Waktu Pengambilan" },
  { field: "statusPermohonan", column: "Status Permohonan" },
  { field: "keteranganDitolak", column: "Keterangan Ditolak" },
  { field: "statusProses", column: "Status Proses" },
  { field: "tiket", column: "Tiket" },
  { field: "kodeLotLelang", column: "Kode Lot Lelang" },
  { field: "nomorValidasi", column: "Nomor Validasi" },
  { field: "tanggalValidasi", column: "Tanggal Validasi" },
  { field: "catatan", column: "catatan" },
  { field: "jarak", column: "jarak" },
  { field: "mergedDocIDValidasiPPh", column: "Merged Doc ID - Validasi PPh" },
  { field: "mergedDocURLValidasiPPh", column: "Merged Doc URL - Validasi PPh" },
  { field: "linkToMergedDocValidasiPPh", column: "Link to merged Doc - Validasi PPh" },
  { field: "documentMergeStatusValidasiPPh", column: "Document Merge Status - Validasi PPh" },
  { field: "mergedDocIDAutoValidasiPPh", column: "Merged Doc ID - auto Validasi PPh" },
  { field: "bantuAutoPPh", column: "bantu_auto_pph" },
  { field: "mergedDocURLAutoValidasiPPh", column: "Merged Doc URL - auto Validasi PPh" },
  { field: "linkToMergedDocAutoValidasiPPh", column: "Link to merged Doc - auto Validasi PPh" },
  { field: "documentMergeStatusAutoValidasiPPh", column: "Document Merge Status - auto Validasi PPh" },
  { field: "mergedDocIDAutoNotifValidasiPPh", column: "Merged Doc ID - auto notif validasi pph" },
  { field: "mergedDocURLAutoNotifValidasiPPh", column: "Merged Doc URL - auto notif validasi pph" },
  { field: "linkToMergedDocAutoNotifValidasiPPh", column: "Link to merged Doc - auto notif validasi pph" },
  { field: "documentMergeStatusAutoNotifValidasiPPh", column: "Document Merge Status - auto notif validasi pph" },
  { field: "deletedAt", column: "Tgl Dihapus" },
  { field: "deletedBy", column: "Dihapus Oleh" },
]

export const ACTIVITY_LOG_MAPPING: FieldMapping[] = [
  { field: "waktu", column: "Waktu" },
  { field: "idPengajuan", column: "ID Pengajuan" },
  { field: "jenisLayanan", column: "Jenis Layanan" },
  { field: "statusLama", column: "Status Lama" },
  { field: "statusBaru", column: "Status Baru" },
  { field: "keterangan", column: "Keterangan" },
]

export const SHEET_MAPPINGS: Record<string, FieldMapping[]> = {
  Monitoring: MONITORING_MAPPING,
  Kuitansi: KUITANSI_MAPPING,
  "Kutipan RL": KUTIPAN_RL_MAPPING,
  "Validasi PPh": VALIDASI_PPH_MAPPING,
  "Activity Log": ACTIVITY_LOG_MAPPING,
}

export const SHEET_ID_COLUMNS: Record<string, { idColumn: string; field: string }> = {
  Kuitansi: { idColumn: "ID KPHL", field: "idKPHL" },
  "Kutipan RL": { idColumn: "ID K-RL", field: "idKRL" },
  "Validasi PPh": { idColumn: "ID VPPh", field: "idVPPh" },
}
